# BOX CONFIGURATION
BLUE = (0, 0, 255)
PURPLE = (128, 0, 128)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
# BLUE = (255, 255, 255)
# MY MOBILE RESOLUTION
SCREEN_WIDTH = 980/1.5
SCREEN_HEIGHT = 476/1.5


CALIBRATION_CIRCLE_RADIUS = 8


# SCREEN_WIDTH = 1024
# SCREEN_HEIGHT = 768
L = int(0.08*SCREEN_WIDTH)
if L % 2 != 0:
    L += 1
BOX_WIDTH = L
BOX_HEIGHT = L
BORDER_RADIUS = 15
BOX_RATIO = 0.1
REAL_BOX_RATIO = 0.3

# Boxes position indicator
TOP_POSITION = "top"
RIGHT_POSITION = "right"
DOWN_POSITION = "down"
LEFT_POSITION = "left"
CENTER_POSITION = "center"

# Boxes frequencies
TOP_FREQ = 30  # HZ
LEFT_FREQ = 30  # HZ #RIGHT
DOWN_FREQ = 30  # HZ
RIGHT_FREQ = 30  # HZ #LEFT
CENTER_FREQ = 30  # HZ


POSITIONS = [TOP_POSITION, RIGHT_POSITION, DOWN_POSITION, LEFT_POSITION]

freq = [TOP_FREQ, RIGHT_FREQ, DOWN_FREQ, LEFT_FREQ]

FREQUENCIES_DICT = {
    TOP_POSITION: TOP_FREQ,
    RIGHT_POSITION: LEFT_FREQ,
    DOWN_POSITION: DOWN_FREQ,
    LEFT_POSITION: RIGHT_FREQ
}

# SESSION CONFIGURATION
PREPARATION_TIME = 1
STIMULATION_TIME = 1
REST_TIME = 1

FRAMERATE = 60
